/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as GuestRouteRouteImport } from './routes/_guest/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuestSignupRouteImport } from './routes/_guest/signup'
import { Route as GuestSigninRouteImport } from './routes/_guest/signin'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedOnboardedRouteRouteImport } from './routes/_authenticated/_onboarded/route'
import { Route as AuthenticatedOnboardedWorkspaceSlugRouteRouteImport } from './routes/_authenticated/_onboarded/$workspaceSlug/route'
import { Route as AuthenticatedOnboardedWorkspaceSlugIndexRouteImport } from './routes/_authenticated/_onboarded/$workspaceSlug/index'
import { Route as AuthenticatedOnboardedWorkspaceSlugSettingsRouteImport } from './routes/_authenticated/_onboarded/$workspaceSlug/settings'
import { Route as AuthenticatedOnboardedWorkspaceSlugInboxRouteImport } from './routes/_authenticated/_onboarded/$workspaceSlug/inbox'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRouteRoute = GuestRouteRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestSignupRoute = GuestSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestSigninRoute = GuestSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => GuestRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardedRouteRoute =
  AuthenticatedOnboardedRouteRouteImport.update({
    id: '/_onboarded',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardedWorkspaceSlugRouteRoute =
  AuthenticatedOnboardedWorkspaceSlugRouteRouteImport.update({
    id: '/$workspaceSlug',
    path: '/$workspaceSlug',
    getParentRoute: () => AuthenticatedOnboardedRouteRoute,
  } as any)
const AuthenticatedOnboardedWorkspaceSlugIndexRoute =
  AuthenticatedOnboardedWorkspaceSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOnboardedWorkspaceSlugRouteRoute,
  } as any)
const AuthenticatedOnboardedWorkspaceSlugSettingsRoute =
  AuthenticatedOnboardedWorkspaceSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedOnboardedWorkspaceSlugRouteRoute,
  } as any)
const AuthenticatedOnboardedWorkspaceSlugInboxRoute =
  AuthenticatedOnboardedWorkspaceSlugInboxRouteImport.update({
    id: '/inbox',
    path: '/inbox',
    getParentRoute: () => AuthenticatedOnboardedWorkspaceSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/verify-email': typeof VerifyEmailRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/signin': typeof GuestSigninRoute
  '/signup': typeof GuestSignupRoute
  '/$workspaceSlug': typeof AuthenticatedOnboardedWorkspaceSlugRouteRouteWithChildren
  '/$workspaceSlug/inbox': typeof AuthenticatedOnboardedWorkspaceSlugInboxRoute
  '/$workspaceSlug/settings': typeof AuthenticatedOnboardedWorkspaceSlugSettingsRoute
  '/$workspaceSlug/': typeof AuthenticatedOnboardedWorkspaceSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/verify-email': typeof VerifyEmailRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/signin': typeof GuestSigninRoute
  '/signup': typeof GuestSignupRoute
  '/$workspaceSlug/inbox': typeof AuthenticatedOnboardedWorkspaceSlugInboxRoute
  '/$workspaceSlug/settings': typeof AuthenticatedOnboardedWorkspaceSlugSettingsRoute
  '/$workspaceSlug': typeof AuthenticatedOnboardedWorkspaceSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_guest': typeof GuestRouteRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/_authenticated/_onboarded': typeof AuthenticatedOnboardedRouteRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_guest/signin': typeof GuestSigninRoute
  '/_guest/signup': typeof GuestSignupRoute
  '/_authenticated/_onboarded/$workspaceSlug': typeof AuthenticatedOnboardedWorkspaceSlugRouteRouteWithChildren
  '/_authenticated/_onboarded/$workspaceSlug/inbox': typeof AuthenticatedOnboardedWorkspaceSlugInboxRoute
  '/_authenticated/_onboarded/$workspaceSlug/settings': typeof AuthenticatedOnboardedWorkspaceSlugSettingsRoute
  '/_authenticated/_onboarded/$workspaceSlug/': typeof AuthenticatedOnboardedWorkspaceSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/verify-email'
    | '/onboarding'
    | '/signin'
    | '/signup'
    | '/$workspaceSlug'
    | '/$workspaceSlug/inbox'
    | '/$workspaceSlug/settings'
    | '/$workspaceSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/verify-email'
    | '/onboarding'
    | '/signin'
    | '/signup'
    | '/$workspaceSlug/inbox'
    | '/$workspaceSlug/settings'
    | '/$workspaceSlug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_guest'
    | '/verify-email'
    | '/_authenticated/_onboarded'
    | '/_authenticated/onboarding'
    | '/_guest/signin'
    | '/_guest/signup'
    | '/_authenticated/_onboarded/$workspaceSlug'
    | '/_authenticated/_onboarded/$workspaceSlug/inbox'
    | '/_authenticated/_onboarded/$workspaceSlug/settings'
    | '/_authenticated/_onboarded/$workspaceSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/signup': {
      id: '/_guest/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof GuestSignupRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/signin': {
      id: '/_guest/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof GuestSigninRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_onboarded': {
      id: '/_authenticated/_onboarded'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedOnboardedRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_onboarded/$workspaceSlug': {
      id: '/_authenticated/_onboarded/$workspaceSlug'
      path: '/$workspaceSlug'
      fullPath: '/$workspaceSlug'
      preLoaderRoute: typeof AuthenticatedOnboardedWorkspaceSlugRouteRouteImport
      parentRoute: typeof AuthenticatedOnboardedRouteRoute
    }
    '/_authenticated/_onboarded/$workspaceSlug/': {
      id: '/_authenticated/_onboarded/$workspaceSlug/'
      path: '/'
      fullPath: '/$workspaceSlug/'
      preLoaderRoute: typeof AuthenticatedOnboardedWorkspaceSlugIndexRouteImport
      parentRoute: typeof AuthenticatedOnboardedWorkspaceSlugRouteRoute
    }
    '/_authenticated/_onboarded/$workspaceSlug/settings': {
      id: '/_authenticated/_onboarded/$workspaceSlug/settings'
      path: '/settings'
      fullPath: '/$workspaceSlug/settings'
      preLoaderRoute: typeof AuthenticatedOnboardedWorkspaceSlugSettingsRouteImport
      parentRoute: typeof AuthenticatedOnboardedWorkspaceSlugRouteRoute
    }
    '/_authenticated/_onboarded/$workspaceSlug/inbox': {
      id: '/_authenticated/_onboarded/$workspaceSlug/inbox'
      path: '/inbox'
      fullPath: '/$workspaceSlug/inbox'
      preLoaderRoute: typeof AuthenticatedOnboardedWorkspaceSlugInboxRouteImport
      parentRoute: typeof AuthenticatedOnboardedWorkspaceSlugRouteRoute
    }
  }
}

interface AuthenticatedOnboardedWorkspaceSlugRouteRouteChildren {
  AuthenticatedOnboardedWorkspaceSlugInboxRoute: typeof AuthenticatedOnboardedWorkspaceSlugInboxRoute
  AuthenticatedOnboardedWorkspaceSlugSettingsRoute: typeof AuthenticatedOnboardedWorkspaceSlugSettingsRoute
  AuthenticatedOnboardedWorkspaceSlugIndexRoute: typeof AuthenticatedOnboardedWorkspaceSlugIndexRoute
}

const AuthenticatedOnboardedWorkspaceSlugRouteRouteChildren: AuthenticatedOnboardedWorkspaceSlugRouteRouteChildren =
  {
    AuthenticatedOnboardedWorkspaceSlugInboxRoute:
      AuthenticatedOnboardedWorkspaceSlugInboxRoute,
    AuthenticatedOnboardedWorkspaceSlugSettingsRoute:
      AuthenticatedOnboardedWorkspaceSlugSettingsRoute,
    AuthenticatedOnboardedWorkspaceSlugIndexRoute:
      AuthenticatedOnboardedWorkspaceSlugIndexRoute,
  }

const AuthenticatedOnboardedWorkspaceSlugRouteRouteWithChildren =
  AuthenticatedOnboardedWorkspaceSlugRouteRoute._addFileChildren(
    AuthenticatedOnboardedWorkspaceSlugRouteRouteChildren,
  )

interface AuthenticatedOnboardedRouteRouteChildren {
  AuthenticatedOnboardedWorkspaceSlugRouteRoute: typeof AuthenticatedOnboardedWorkspaceSlugRouteRouteWithChildren
}

const AuthenticatedOnboardedRouteRouteChildren: AuthenticatedOnboardedRouteRouteChildren =
  {
    AuthenticatedOnboardedWorkspaceSlugRouteRoute:
      AuthenticatedOnboardedWorkspaceSlugRouteRouteWithChildren,
  }

const AuthenticatedOnboardedRouteRouteWithChildren =
  AuthenticatedOnboardedRouteRoute._addFileChildren(
    AuthenticatedOnboardedRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedOnboardedRouteRoute: typeof AuthenticatedOnboardedRouteRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedOnboardedRouteRoute:
    AuthenticatedOnboardedRouteRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface GuestRouteRouteChildren {
  GuestSigninRoute: typeof GuestSigninRoute
  GuestSignupRoute: typeof GuestSignupRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestSigninRoute: GuestSigninRoute,
  GuestSignupRoute: GuestSignupRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  GuestRouteRoute: GuestRouteRouteWithChildren,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
